apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-monitoring
  namespace: prometheus

---
apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: prometheus-monitoring
    rules:
      - apiGroups: 
        - ""
        resources: 
        - namespaces
        - pods
        - nodes
        - endpoints
        - services
        - configmaps
        - nodes/proxy
        - ingresses
        verbs: 
        - get
        - watch
        - list
      - apiGroups:
        - "extensions"
        resources:
        - ingresses
        verbs:
        - get
        - watch
        - list
      - nonResourceURLs:
        - /metrics
        verbs: 
        - get
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: prometheus-monitoring
    subjects:
    - kind: ServiceAccount
      name: prometheus-monitoring
      namespace: prometheus
    roleRef:
      kind: ClusterRole
      name: prometheus-monitoring
      apiGroup: rbac.authorization.k8s.io
kind: List

---
apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s # By default, scrape targets every 15 seconds.
      external_labels:
        monitor: 'heatseaker'

    scrape_configs:
      - job_name: 'heatseaker'
        scrape_interval: 5s
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
        - source_labels: [__meta_kubernetes_node_address_InternalIP]
          regex: (.+)
          target_label: __address__
          replacement: ${1}:8000
kind: ConfigMap
metadata:
  creationTimestamp: "2019-06-29T17:51:39Z"
  name: prometheus-config
  namespace: prometheus

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccount: prometheus-monitoring
      securityContext:
        fsGroup: 65534
      containers:
      - name: server
        image: prom/prometheus:v2.10.0
        command:
        - prometheus
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.retention.size=2GB
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: data
          mountPath: /prometheus
        readinessProbe:
          httpGet:
            path: /status
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: prometheus-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 3Gi

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  selector:
    app: prometheus
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    name: http-port
    protocol: TCP
