apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: v1
data:
  prometheus.yaml: |
    global:
      scrape_interval:     15s # By default, scrape targets every 15 seconds.
      external_labels:
        monitor: 'heatseaker'

    scrape_configs:
      - job_name: 'heatseaker'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:8000']
kind: ConfigMap
metadata:
  creationTimestamp: "2019-06-29T17:51:39Z"
  name: prometheus-config
  namespace: prometheus

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        fsGroup: 65534
      containers:
      - name: server
        image: prom/prometheus:v2.10.0
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yaml
          subPath: prometheus.yaml
        - name: data
          mountPath: /prometheus
        readinessProbe:
          httpGet:
            path: /status
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: prometheus-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClass: local-path
      resources:
        requests:
          storage: 3Gi

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  selector:
    app: prometheus
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9090
    name: http-port
    protocol: TCP
